name: Build dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]   # PRs cujo destino é dev

concurrency:
  group: ci-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: build-and-test (dev)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - run: pnpm i
      - run: pnpm build
      - run: pnpm test
